version: '3'
services:
  esphome:
    container_name: esphomestable
    image: ghcr.io/esphome/esphome:stable
    volumes:
      - /path/to/esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    environment:
      - USERNAME=test
      - PASSWORD=ChangeMe