---
# Luxmeter
#
# a simple ESPHome integration to make an luxmeter
# © Maarten Schmeitz
#
substitutions:
  device_name: home-assistant-luxmeter
  friendly_name: Home Assistant LuxMeter
  project_version: "0.0.1"
  device_description: "A simple project luxmeter - ESP8266 Generic"


esphome:
  name: '${device_name}'
  friendly_name: '${device_description}'
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true
  name_add_mac_suffix: true
  min_version: 2024.6.0
  project:
    name: "scns.myESPHome"
    version: "${project_version}"

esp32:
  platform: ESP8266
  board: d1_mini

# To be able to get logs from the device via serial and api.
logger:

# API is a requirement of the dashboard import.
api:

# OTA is required for Over-the-Air updating
ota:
  - platform: esphome

wifi:
  # Set up a wifi access point using the device name above
  ap:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device.
captive_portal: