name: "Documentation"
description: "Create an issue to improve the documentation of the myESPhome Project"
labels: ["documentation", "triage:not-checked"]
body:
  - type: markdown
    attributes:
      value: |
        Create a new issue regarding the myESPhome documentation
  - type: textarea
    id: repro
    attributes:
      label: Body of the issue
      description: Please provide one distinct thing to fix or a clearly defined enhancement
    validations:
      required: true
