substitutions:
  project_version: "2.0.11"
  device_description: "${device_name} build by Maarten Schmeitz (scns). Version ${project_version}. (https://github.com/scns)"
  date: "11-09-2024"

preferences:
  flash_write_interval: 120min 
  
safe_mode:

web_server:
  version: 3
  port: 80

wifi:
  ap:
  
improv_serial:

captive_portal:

api:

ota:
  - platform: esphome
    id: ota_esphome
  - platform: http_request
    id: ota_http_request

http_request:
  verify_ssl: false

# ⬇ Enable logging ⬇ # 
logger:
  level: INFO
  tx_buffer_size: 100
  esp8266_store_log_strings_in_flash: false

time:
- platform: homeassistant
  id: time_homeassistant
  on_time_sync:
    - component.update: ${device_name}_uptime_timestamp  

# ⬇ versie verbinding informatie sensoren voor in ha ⬇ #
#------------------------#  sensoren #------------------------#
sensor:

  - platform: uptime
    id: ${device_name}_uptime

  - platform: template
    id: ${device_name}_uptime_timestamp
    name: "${device_name} online sinds"
    device_class: "timestamp"
    accuracy_decimals: 0
    update_interval: never
    icon: 'mdi:clock-start'
    entity_category: diagnostic
    lambda: |-
      static float timestamp = (
        id(time_homeassistant).utcnow().timestamp - id(${device_name}_uptime).state
      );
      return timestamp;  


  # WiFi signal
  - platform: wifi_signal
    name: "${device_name} - WiFi Signal"
    update_interval: 120s

# ⬇ versie verbinding informatie text_sensoren voor in ha ⬇ #
#------------------------#  text_sensoren #------------------------#
text_sensor:
  - platform: template
    name: "${device_name}_versie"
    id: ${device_name}_versie
    icon: 'mdi:alpha-v-circle-outline' 
    update_interval: 6h
    entity_category: diagnostic
    lambda: |-
      return {"${project_version}"};

  - platform: wifi_info
    ip_address:
      name: "${device_name} IP-adres"
      id: ${device_name}_ip_adres
      icon: mdi:ip-network

    mac_address:
      name: "${device_name} Mac-adres"
      id: ${device_name}_mac_adres
      icon: mdi:folder-key-network-outline

# ⬇ versie verbinding informatie switches voor in ha ⬇ #


# ⬇ versie verbinding informatie buttons voor in ha ⬇ #
#------------------------#  buttons #------------------------#

button:
  - platform: restart
    name: "${device_name} Restart"
    entity_category: diagnostic
  
  # Factory Reset Switch from ESPHome v2022.09
  - platform: factory_reset
    name: "${device_name} Restart with Factory Default Settings"
    entity_category: diagnostic
    disabled_by_default: True

 # safe mode button
  - platform: safe_mode
    name: "${device_name} Safe Mode"
    entity_category: diagnostic
    disabled_by_default: True

  - platform: template
    id: check_for_update_button
    name: ${device_name} Check for firmware update
    device_class: update
    on_press:
      then:
        - component.update: update_http_request