# CHANGEME: Set these variable to your liking
title: myESPhome projects
description: Powered by ESPHome and ESP Web Tools
#theme: jekyll-theme-slate
remote_theme: chrisrhymes/bulma-clean-theme@v1.0.0
