---
# DTH22 Sensor
#
# A simple ESPHome integration for DTH22 sensor with Home Assistant
# © Maarten Schmeitz
#
substitutions:
  device_name: "DTH22"
  
esphome:
  name: '${device_name}'
  name_add_mac_suffix: true
  comment: '${device_description}'
  project:
    name: "scns.myESPHome_${device_name}"
    version: "${project_version}"
  min_version: 2024.6.0

esp8266:
  board:  d1_mini
  restore_from_flash: true


dashboard_import:
  package_import_url: github://scns/myESPhome/esphome/dth22.yaml

packages:
  remote_package:
    url: https://github.com/scns/myESPhome
    ref: main
    files:
      - esphome/package/dth22_update.yaml
      - esphome/package/basis_esp8266.yaml #specific esp8266 basis settings
      - esphome/package/dth22.yaml
      - esphome/package/basis_settings.yaml
    refresh: 0d