---
# vindriktning 
#
# a simple ESPHome integration to make an Kemo M152 to work with Home Assistant 
# © Maarten Schmeitz
#
substitutions:
  device_name: "kemo_m142"
  
esphome:
  name: '${device_name}'
  name_add_mac_suffix: true
  comment: '${device_description}'
  project:
    name: "scns.myESPHome_${device_name}"
    version: "${project_version}"
  min_version: 2024.6.0

esp8266:
  board:  d1_mini
  restore_from_flash: true


dashboard_import:
  package_import_url: github://scns/myESPhome/esphome/kemo_m152.yaml

packages:
  remote_package:
    url: https://github.com/scns/myESPhome
    ref: main
    files:
      - esphome/package/kemo_m152_update.yaml
      - esphome/package/basis_esp8266.yaml #specific esp8266 basis settings
      - esphome/package/kemo_m152.yaml
      - esphome/package/basis_settings.yaml
    refresh: 0d