name: Build
# Build the ESPHome firmwares for the MyESPhome project.
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
 # release:
   # types: [published]

jobs:
  build-luxmeter:
    name: Build firmware Luxmeter 🛠️
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      yaml-file: esphome/luxmeter.yaml
        
      esphome-version: 2024.10.0
      release-url: "https://github.com/scns/myESPhome/releases"
      release-summary: "** Check the release notes for more information. **"

  build-vindriktning:
    name: Build firmware vindriktning 🛠️
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      yaml-file: esphome/vindriktning.yaml
        
      esphome-version: 2024.10.0
      release-url: "https://github.com/scns/myESPhome/releases"
      release-summary: "** Check the release notes for more information. **"

  build-bluetoothproxy:
    name: Build firmware bluetoothproxy 🛠️
    uses: esphome/workflows/.github/workflows/build.yml@main
    with:
      yaml-file: esphome/bluetoothproxy.yaml
        
      esphome-version: 2024.10.0
      release-url: "https://github.com/scns/myESPhome/releases"
      release-summary: "** Check the release notes for more information. **"


      #esphome/garagedoor.yaml
      #esphome/ds18b20.yaml
      #esphome/ds18b20_beta.yaml

              
  comment-luxmeter:
    if: github.event_name == 'pull_request'
    name: Comment on PR
    runs-on: ubuntu-latest
    needs:
      - build-luxmeter
    steps:
      - name: Comment on PR
        uses: actions/github-script@v7.0.1
        with:
          script: |-
            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.runId,
            })
            const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts/${artifacts['data']['artifacts'][0]['id']}`
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Firmware built successfully! :tada:

            [Download][download] and extract the firmware to install with https://web.esphome.io

            Make sure to choose \`luxmeter-esp8266.factory.bin\`.

            [download]: ${url}`
            })

  comment-vindriktning:
    if: github.event_name == 'pull_request'
    name: Comment on PR
    runs-on: ubuntu-latest
    needs:
        - build-vindriktning
    steps:
        - name: Comment on PR
          uses: actions/github-script@v7.0.1
          with:
            script: |-
                const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    run_id: context.runId,
                })
                const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts/${artifacts['data']['artifacts'][0]['id']}`
                await github.rest.issues.createComment({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    body: `Firmware built successfully! :tada:

                [Download][download] and extract the firmware to install with https://web.esphome.io

                Make sure to choose \`vindriktning-esp8266.factory.bin\`.

                [download]: ${url}`
                })

  comment-bluetoothproxy:
    if: github.event_name == 'pull_request'
    name: Comment on PR
    runs-on: ubuntu-latest
    needs:
        - build-bluetoothproxy
    steps:
        - name: Comment on PR
          uses: actions/github-script@v7.0.1
          with:
                script: |-
                    const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        run_id: context.runId,
                    })
                    const url = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts/${artifacts['data']['artifacts'][0]['id']}`
                    await github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: `Firmware built successfully! :tada:

                    [Download][download] and extract the firmware to install with https://web.esphome.io

                    Make sure to choose \`bluetoothproxy-esp32.factory.bin\`.

                    [download]: ${url}`
                    })